### ISSUE TITLE
can't  mex CSH_code_v3

### ISSUE THREAD

**Issue by GodBaoBao** [PetterS/patch-inpainting#1]
windows10,VS2017,MatlabR2017b
problem:
knn.cpp
 fatal error C1189: #error:  <hash_set> is deprecated
and will be REMOVED. Please use <unordered_set>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that
you have received this warning.

**Comment by PetterS** [comment]
If you make a PR I will accept it.

**Comment by GodBaoBao** [comment]
what is PR ?

**Comment by PetterS** [comment]
Pull request.
